Владимир Кирилкин ПИ18-2
fa-python-network/6_Web_server pull request #19
Opened 2019-11-29 09:40 UTC by v1ack

2019-11-29 19:36 UTC, v1ack commented
Асинхронность подъехала

2019-11-29 20:49 UTC, flymedllva approved these changes

2019-11-29 20:49 UTC, FlymeDllVa commented on Dockerfile
> +ADD requirements*.txt /mnt/
Так ну короче, тут все плохо. Почему PIP 👎 , а не Poetry 👍

2019-11-29 20:49 UTC, FlymeDllVa commented on server/server.py
> +    CONTENT_TYPES = dict(
Слишком знакомо

2019-11-29 20:49 UTC, FlymeDllVa commented on server/server.py
> +Server: SelfMadeServer v0.0.1
Съехало

2019-11-29 20:49 UTC, FlymeDllVa commented on server/server.py
> +        super().__init__(status=status)
По приколу?

2019-11-29 20:49 UTC, FlymeDllVa commented on server/server.py
> +    HTTP_REQUEST = re.compile(
Регулярка ради 1 использования, ну ок. Там вроде и так все удобно

2019-11-29 20:49 UTC, FlymeDllVa commented on server/server.py
> +def handler(request):
Забыл тип указать и стрелочку нарисовать

2019-11-29 20:49 UTC, FlymeDllVa commented on server/server.py
> +        address = self.address.split("?")
Это прикольно после регулярки вверху

2019-11-29 20:49 UTC, FlymeDllVa commented on server/__main__.py
> +from aiomisc import entrypoint
А без AIO? Там пропарсить, запустить и так просто :/

2019-11-29 20:49 UTC, FlymeDllVa commented on server/__main__.py
> +    from .http_server import HTTPServer
Ну это лайк 👍

2019-11-29 20:49 UTC, FlymeDllVa commented on server/http_classes.py
> +Cache-Control: max-age=8600
Мне кажется если его не настраивать, то смысла писать нет

2019-11-29 20:49 UTC, FlymeDllVa commented on server/http_server.py
> +    def __init__(self, address: str, port: int, **kwargs):
kwargs для настоящих пацанов

2019-11-29 20:49 UTC, FlymeDllVa commented on server/http_server.py
> +    async def start(self):
Мне кажется это бесполезно в отдельный класс выносить, ну типа опять **задел на будущее**. Ок

2019-11-29 20:49 UTC, FlymeDllVa commented on server/http_server.py
> +        except Exception as e:
А мне говоришь не юзать Exception, я плакать

2019-11-29 20:49 UTC, FlymeDllVa commented on server/http_server.py
> +    server: "asyncio.Server"
Это поле название сервиса или ты хотел отправить это в заголовке, но что-то забыл?

2019-11-29 21:05 UTC, v1ack commented on server/http_server.py
> +        except Exception as e:
Аххахахаха, я уберу

2019-11-29 21:05 UTC, v1ack commented on server/http_server.py
> +    server: "asyncio.Server"
Аннотация типа переменной. Типа чтобы в init `self.server = None` не писать

2019-11-29 21:05 UTC, v1ack commented on server/http_server.py
> +    def __init__(self, address: str, port: int, **kwargs):
Лишним не будет

2019-11-29 21:05 UTC, v1ack commented on server/http_server.py
> +    async def start(self):
Это сервис. Сервис это круто. 

Больше аргументов нет

2019-11-29 21:05 UTC, v1ack commented on server/http_classes.py
> +Cache-Control: max-age=8600
Почему? Оно и так работает, на картинках можно заметить

2019-11-29 21:05 UTC, v1ack commented on server/__main__.py
> +    from .http_server import HTTPServer
♿

2019-11-29 21:05 UTC, v1ack commented on server/__main__.py
> +from aiomisc import entrypoint
Это только для запуска. Лишним не будет

2019-11-29 21:09 UTC, FlymeDllVa commented on server/http_classes.py
> +Cache-Control: max-age=8600
> Почему? Оно и так работает, на картинках можно заметить

Я про смысловую нагрузку

2019-11-29 21:10 UTC, FlymeDllVa commented on server/__main__.py
> +from aiomisc import entrypoint
Я бы вообще, кстати, AIOHTTP сразу воткнул

2019-11-29 21:12 UTC, v1ack commented on server/__main__.py
> +from aiomisc import entrypoint
Я бы тоже, но не думаю что Михаил Викторович одобрит

2019-11-29 21:17 UTC, v1ack commented on server/server.py
> +Server: SelfMadeServer v0.0.1
Что? вроде норм всё

2019-11-29 21:18 UTC, v1ack commented on server/server.py
> +        super().__init__(status=status)
Это очень полезный и функциональный класс, который очень сильно помогает читаемости кода и сокращает повторение

2019-11-29 21:18 UTC, FlymeDllVa commented on server/server.py
> +Server: SelfMadeServer v0.0.1
Код некрасивый :/ Типа начало строки, а в питоне отступы

2019-11-29 21:19 UTC, v1ack commented on server/server.py
> +    HTTP_REQUEST = re.compile(
Регулярки круче сплита

2019-11-29 21:19 UTC, v1ack commented on server/server.py
> +def handler(request):
Соглашусь

2019-11-29 21:19 UTC, v1ack commented on server/server.py
> +        address = self.address.split("?")
Но без сплита никуда

2019-11-29 21:20 UTC, FlymeDllVa commented on server/server.py
> +        super().__init__(status=status)
Да я про super)

2019-11-29 21:22 UTC, v1ack commented on server/server.py
> +        super().__init__(status=status)
Без него никак

2019-11-29 21:23 UTC, v1ack commented on server/server.py
> +Server: SelfMadeServer v0.0.1
```
f"HTTP/1.1 {self.status} {self.STATUS_CODES[self.status]}" /
f"Server: SelfMadeServer v0.0.1"
```
Так будет лучше?

2019-11-29 21:25 UTC, FlymeDllVa commented on server/server.py
> +Server: SelfMadeServer v0.0.1
Мне кажется да, ну вообще вроде как линтер не ругается на """""". Во 2 строчке f лишняя. Прост мне кажется, что в большом проекте я бы сделал по классу для каждого параметра и уже им кормил данные, которые они обрабатывали и тупо дописывали в headers

2019-11-29 21:42 UTC, flymedllva requested changes
- Неправильный конец у headers. Должен быть [section 4.1 of RFC 2616](https://tools.ietf.org/html/rfc2616#section-4.1)
- 404 не кидает HTML код. Не все браузеры 404 именно из ответа отрисовывают

2019-11-29 21:42 UTC, FlymeDllVa commented on server/http_classes.py
>  """.encode()
В конце **headers** должны быть другие отступы. **"\r\n\r\n"** кажется, точно не помню. Без них некоторые браузеры и большенство программ работающих с API тупо не загрузят страничку в силу того, что у них разные кодировки.

2019-12-12 14:25 UTC, koroteevmv commented
Я вам зачитываю, но вы слишком увлекаетесь сложным деплоем)

2019-12-12 14:25 UTC, closed without merging